[package]
name = "DioxusClient"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", branch = "master"}
dioxus-web = { git = "https://github.com/DioxusLabs/dioxus", branch = "master"}
reqwest = "0.11.14"
